- DesktopModules/AgapeConnect/Stories/StoryMixer.ascx
- DesktopModules/AgapeConnect/Stories/StoryMixer.ascx.vb
no longer necessary since DNN 7.2
> removed jquery registering

- DesktopModules/AgapeConnect/Stories/AddEditStory.ascx
- DesktopModules/AgapeConnect/Stories/AddEditStory.ascx.vb
All new articles will be put in the channel of origin.
> Replaced channel dropdown with label

- DesktopModules/AgapeConnect/EditStaffProfile/App_LocalResources/EditStaffProfile.ascx.fr-FR.Portal-0.resx
- DesktopModules/AgapeConnect/EditStaffProfile/App_LocalResources/EditStaffProfile.ascx.resx
- DesktopModules/AgapeConnect/EditStaffProfile/EditStaffProfile.ascx
- DesktopModules/AgapeConnect/EditStaffProfile/EditStaffProfile.ascx.vb
- DesktopModules/AgapeConnect/StaffAdmin/Controls/App_LocalResources/Departments.ascx.fr-FR.Portal-0.resx
- DesktopModules/AgapeConnect/StaffAdmin/Controls/App_LocalResources/Departments.ascx.resx
- DesktopModules/AgapeConnect/StaffAdmin/Controls/App_LocalResources/Leaders.ascx.resx
- DesktopModules/AgapeConnect/StaffAdmin/Controls/App_LocalResources/Plebs.ascx.fr-FR.Portal-0.resx
- DesktopModules/AgapeConnect/StaffAdmin/Controls/App_LocalResources/Plebs.ascx.resx
- DesktopModules/AgapeConnect/StaffAdmin/Controls/App_LocalResources/acImage.ascx.fr-FR.Portal-0.resx
- DesktopModules/AgapeConnect/StaffAdmin/Controls/App_LocalResources/acImage.ascx.resx
- DesktopModules/AgapeConnect/StaffAdmin/Controls/Departments.ascx
- DesktopModules/AgapeConnect/StaffAdmin/Controls/Departments.ascx.vb
- DesktopModules/AgapeConnect/StaffAdmin/Controls/Leaders.ascx.vb
- DesktopModules/AgapeConnect/StaffAdmin/Controls/Plebs.ascx
- DesktopModules/AgapeConnect/StaffAdmin/Controls/Plebs.ascx.vb
- DesktopModules/AgapeConnect/StaffAdmin/Controls/acImage.ascx
- DesktopModules/AgapeConnect/StaffAdmin/Controls/acImage.ascx.vb
Fixes some jquery problems and adds translation to the editstaffprofile module and embedded controls
> (OIB-114) and translate editstaffprofile

- App_Code/Stories/StoryFunctions.vb
- DesktopModules/AgapeConnect/Stories/AddEditStory.ascx
- DesktopModules/AgapeConnect/Stories/App_LocalResources/StorySettings.ascx.resx
- DesktopModules/AgapeConnect/Stories/App_LocalResources/TagSettings.ascx.fr-FR.resx
- DesktopModules/AgapeConnect/Stories/App_LocalResources/Unpublished.ascx.fr-FR.resx
- DesktopModules/AgapeConnect/Stories/App_LocalResources/ViewStories.ascx.fr-FR.resx
- DesktopModules/AgapeConnect/Stories/Module.css
- DesktopModules/AgapeConnect/Stories/StoryMixer.ascx.vb
- DesktopModules/AgapeConnect/Stories/StorySettings.ascx
- DesktopModules/AgapeConnect/Stories/StorySettings.ascx.vb
- DesktopModules/AgapeConnect/Stories/TagSettings.ascx
- DesktopModules/AgapeConnect/Stories/TagSettings.ascx.vb
- DesktopModules/AgapeConnect/Stories/Unpublished.ascx
- DesktopModules/AgapeConnect/Stories/ViewStories.ascx.vb
- DesktopModules/AgapeConnect/Stories/controls/List-Fr2.ascx.vb
- DesktopModules/AgapeConnect/Stories/controls/ListFullWidth-Fr.ascx.vb
- DesktopModules/AgapeConnect/Stories/controls/TagList-Fr.ascx
- DesktopModules/AgapeConnect/Stories/templates/France-RessourceView.html
Final changes to Stories before showing to Communications.
Jon - David will do the review!
> France ressources

- Portals/_default/Containers/20037-UnlimitedColorPack-023/Container-1-color1.ascx
- Portals/_default/Containers/20037-UnlimitedColorPack-023/Container-1-color2.ascx
- Portals/_default/Containers/20037-UnlimitedColorPack-023/Container-1-color3.ascx
- Portals/_default/Containers/20037-UnlimitedColorPack-023/Container-2-color1.ascx
- Portals/_default/Containers/20037-UnlimitedColorPack-023/Container-2-color2.ascx
- Portals/_default/Containers/20037-UnlimitedColorPack-023/Container-2-color3.ascx
- Portals/_default/Containers/20037-UnlimitedColorPack-023/Container-3.ascx
- Portals/_default/Containers/20037-UnlimitedColorPack-023/Container-5-color1.ascx
- Portals/_default/Containers/20037-UnlimitedColorPack-023/Container-5-color2.ascx
- Portals/_default/Containers/20037-UnlimitedColorPack-023/Container-5-color3.ascx
- Portals/_default/Containers/20037-UnlimitedColorPack-023/H1 Container-color1.ascx
- Portals/_default/Containers/20037-UnlimitedColorPack-023/H1 Container-color3.ascx
- Portals/_default/Containers/20037-UnlimitedColorPack-023/H2 Container-color1.ascx
- Portals/_default/Containers/20037-UnlimitedColorPack-023/H2 Container-color2.ascx
- Portals/_default/Containers/20037-UnlimitedColorPack-023/H2 Container-color3.ascx
- Portals/_default/Containers/20037-UnlimitedColorPack-023/H3 Container-color1.ascx
- Portals/_default/Containers/20037-UnlimitedColorPack-023/H3 Container-color2.ascx
- Portals/_default/Containers/20037-UnlimitedColorPack-023/H3 Container-color3.ascx
- Portals/_default/Containers/20037-UnlimitedColorPack-023/No Title.ascx
- Portals/_default/Containers/AgapeBlue/BlueStripe.ascx
- Portals/_default/Containers/AgapeBlue/Green.ascx
- Portals/_default/Containers/AgapeBlue/GreenStripe.ascx
- Portals/_default/Containers/AgapeBlue/NoTitle.ascx
- Portals/_default/Containers/AgapeBlue/RedStripe.ascx
- Portals/_default/Containers/AgapeBlue/Title_Grey.ascx
- Portals/_default/Containers/AgapeBlue/blue.ascx
- Portals/_default/Containers/AgapeBlue/brown.ascx
- Portals/_default/Containers/AgapeBlue/plum.ascx
- Portals/_default/Containers/AgapeBlue/turquoise.ascx
- Portals/_default/Containers/AgapeFR/ExpandableBox.ascx
This was causing containers not to load after the upgrade.
>  Removed references to depreciated SolPartActions in containers

- App_Code/Stories/StoryFunctions.vb
- DesktopModules/AgapeConnect/Stories/AddEditStory.ascx.vb
- DesktopModules/AgapeConnect/Stories/StorySettings.ascx
- DesktopModules/AgapeConnect/Stories/StorySettings.ascx.vb
David, the changes to how the latitude and longitude are set.
> France map

- App_Code/Stories/StoryFunctions.vb
- DesktopModules/AgapeConnect/Stories/AddEditStory.ascx.vb
- DesktopModules/AgapeConnect/Stories/App_LocalResources/StoryMixer.ascx.fr-FR.resx
- DesktopModules/AgapeConnect/Stories/App_LocalResources/StoryMixer.ascx.resx
- DesktopModules/AgapeConnect/Stories/Module.css
- DesktopModules/AgapeConnect/Stories/StoryMixer.ascx
- DesktopModules/AgapeConnect/Stories/StoryMixer.ascx.vb
- DesktopModules/AgapeConnect/Stories/StorySettings.ascx.vb
- DesktopModules/AgapeConnect/Stories/TagSettings.ascx.vb
- DesktopModules/AgapeConnect/Stories/Unpublished.ascx.vb
- DesktopModules/AgapeConnect/Stories/ViewStory.ascx
- DesktopModules/AgapeConnect/Stories/ViewStory.ascx.vb
- DesktopModules/AgapeConnect/Stories/controls/App_LocalResources/SuperPowers.ascx.fr-FR.resx
- DesktopModules/AgapeConnect/Stories/controls/SuperPowers.ascx
- DesktopModules/AgapeConnect/Stories/controls/SuperPowers.ascx.vb
David or Trent - this is for you...
> France publish

- DesktopModules/AgapeConnect/Stories/ViewStory.ascx.vb
> fixed 404 page error not working for stories not found.

- DesktopModules/AgapeConnect/Stories/templates/France-RessourceView.html
- DesktopModules/AgapeConnect/Stories/templates/France-StoryView.html
- DesktopModules/AgapeConnect/Stories/templates/France-StoryViewRecrutement.html
- Install-RunMeAsAdministor.bat
- Portals/_default/Skins/AgapeFR/controls/Footer.ascx
- SiteAnalytics.config
- Uninstall-RunMeAsAdministor.bat
Trent here is the pull request
> France action form

- Install-RunMeAsAdministor.bat
- Portals/_default/Skins/AgapeFR/controls/Footer.ascx
- SiteAnalytics.config
> France analytics

- SiteAnalytics.config
Decided to do this differently. Added the listeners elsewhere and removed from this one file.
> removed listeners from this file

- DesktopModules/DnnSharp/ActionForm/App_LocalResources/Form.fr-FR.resx
- DesktopModules/DnnSharp/ActionForm/App_LocalResources/Reports.fr-Fr.resx
- DesktopModules/DnnSharp/ActionForm/App_LocalResources/Reports.resx
- Install-RunMeAsAdministor.bat
- Uninstall-RunMeAsAdministor.bat
It is best if David looks at these translations.
> Action form translation bug fix

- App_Code/Stories/StoryFunctions.vb
- DesktopModules/AgapeConnect/Stories/AddEditStory.ascx
- DesktopModules/AgapeConnect/Stories/AddEditStory.ascx.vb
- DesktopModules/AgapeConnect/Stories/Module.css
- DesktopModules/AgapeConnect/Stories/StoryMixer.ascx
- DesktopModules/AgapeConnect/Stories/StoryMixer.ascx.vb
- DesktopModules/AgapeConnect/Stories/ViewStory.ascx
- DesktopModules/AgapeConnect/Stories/ViewStory.ascx.vb
Maps can once again be seen and locations can be choosen. Google now requires a key for the maps api.
> France location picker

- DesktopModules/DnnSharp/ActionForm/App_LocalResources/Form.fr-FR.resx
- Portals/_default/Containers/AgapeFR/ActionForm.css
Small styling and translation changes for the new form.
> France actionform enhancements

- App_Code/Stories/StoryFunctions.vb
- DesktopModules/AgapeConnect/Stories/controls/ListFullWidth-Fr.ascx
- DesktopModules/AgapeConnect/Stories/controls/Rotator1-Fr.ascx
- DesktopModules/AgapeConnect/Stories/controls/Rotator2-Fr.ascx
- DesktopModules/AgapeConnect/Stories/js/videopopup.js
- Portals/_default/Containers/AgapeFR/Ressource.css
Trent, you'll need to do a rebase because you have edited some of these files in your responsive branch.
> Fr ressources fix

- App_Code/Stories/StoryFunctions.vb
- DesktopModules/AgapeConnect/Stories/ViewStories.ascx.vb
- DesktopModules/AgapeConnect/Stories/ViewStory.ascx
- DesktopModules/AgapeConnect/Stories/controls/Rotator2-Fr.ascx
- DesktopModules/AgapeConnect/Stories/templates/France-RessourceView.html
- DesktopModules/AgapeConnect/Stories/templates/France-StoryView.html
- DesktopModules/AgapeConnect/Stories/templates/France-StoryViewRecrutement.html
Removing addthis URL hashtag from templates and viewstory. 
I have a small move of click counting from ViewStories to StoryFunctions.
Will move these small changes into prod tomorrow as I have already put the templates into production.
> France SEO

- DesktopModules/Admin/RadEditorProvider/ToolsFile/ToolsFile.PortalId.0.xml
@trentschaller 
Going to put this little change in Prod now.
> Added Agape Sans Frontieres

- Portals/_default/Skins/AgapeFR/App_LocalResources/SharedResources.fr-FR.resx
- Portals/_default/Skins/AgapeFR/controls/Footer.ascx
Quick addition to footer before May 25.
> Privacy Policy link added to Footer

- Install-RunMeAsAdministor.bat
- Uninstall-RunMeAsAdministor.bat
Going to merge this myself! A small change to install/uninstall batch files.
> Updated the hardlinks between localfiles and GitHub.

- DesktopModules/AgapeConnect/Stories/controls/Rotator1-Fr.ascx
- DesktopModules/AgapeConnect/Stories/controls/Rotator2-Fr.ascx
> video story not playing on click
